#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=40
#SBATCH --time=22:00:00
#SBATCH --mail-type=END --mail-user=gfranco@sissa.it
#SBATCH --mem=63500mb

folder=10_WBSG
#mkdir ${folder}
#1000 200 100 66.6 50 40 33.3 28.7 25 22.2 20
for i in 25 22.2 20
do
# 7.96
   time ./a.out ${i} 7.9 &> ${folder}/Latency_${i}.txt
#   mv Latency.txt ${folder}/Latency_${i}.txt	
   echo ${i}
done
